name: metis-env

channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.6
  - flask=1.0.2
  - ftfy=4.4.3
  - gunicorn=19.9.0
  - imbalanced-learn=0.3.1
  - jsonschema=2.6.0
  - matplotlib=2.1.2
  - mlxtend=0.10.0
  - nltk=3.2.5
  - pandas=0.22.0
  - pytest=3.3.2
  - pytorch=0.4.1
  - scikit-learn=0.19.1
  - spacy=2.0.11
  - cython=0.29
  - keras=2.2.4
  - tensorflow=1.10.0
  - flasgger=0.9.2
  - python-slugify=1.2.6
  - pip:
    - git+https://github.com/alisdairv/allennlp.git@increment-flask
    - git+https://www.github.com/keras-team/keras-contrib.git
